name: 'Blog | Mohamad Rido'
description: 'About how to & my experiences'
author: 'Mohamad Rido'
email: 'mohamadrido@mail.ru'
permalink: /:title
plugin:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
markdown: kramdown
highlighter: rouge
paginate: 12
